INSERT INTO PLANE_CARD (multiverse_id, name, type, scryfall_uri) VALUES
    (423590,'Academy at Tolaria West','plane','https://scryfall.com/card/opca/9/academy-at-tolaria-west'),
    (423592,'Agyrem','plane','https://scryfall.com/card/opca/11/agyrem'),
    (423593,'Akoum','plane','https://scryfall.com/card/opca/12/akoum'),
    (423594,'Aretopolis','plane','https://scryfall.com/card/opca/13/aretopolis'),
    (423595,'Astral Arena','plane','https://scryfall.com/card/opca/14/astral-arena'),
    (423596,'Bant','plane','https://scryfall.com/card/opca/15/bant'),
    (423597,'Bloodhill Bastion','plane','https://scryfall.com/card/opca/16/bloodhill-bastion'),
    (423598,'Celestine Reef','plane','https://scryfall.com/card/opca/17/celestine-reef'),
    (423599,'Cliffside Market','plane','https://scryfall.com/card/opca/18/cliffside-market'),
    (423601,'Edge of Malacol','plane','https://scryfall.com/card/opca/20/edge-of-malacol'),
    (423602,'Eloren Wilds','plane','https://scryfall.com/card/opca/21/eloren-wilds'),
    (423604,'Feeding Grounds','plane','https://scryfall.com/card/opca/23/feeding-grounds'),
    (423605,'Fields of Summer','plane','https://scryfall.com/card/opca/24/fields-of-summer'),
    (423607,'Furnace Layer','plane','https://scryfall.com/card/opca/26/furnace-layer'),
    (423608,'Gavony','plane','https://scryfall.com/card/opca/27/gavony'),
    (423609,'Glen Elendra','plane','https://scryfall.com/card/opca/28/glen-elendra'),
    (423610,'Glimmervoid Basin','plane','https://scryfall.com/card/opca/29/glimmervoid-basin'),
    (423611,'Goldmeadow','plane','https://scryfall.com/card/opca/30/goldmeadow'),
    (423612,'Grand Ossuary','plane','https://scryfall.com/card/opca/31/grand-ossuary'),
    (423614,'Grixis','plane','https://scryfall.com/card/opca/33/grixis'),
    (423615,'Grove of the Dreampods','plane','https://scryfall.com/card/opca/34/grove-of-the-dreampods'),
    (423616,'Hedron Fields of Agadeem','plane','https://scryfall.com/card/opca/35/hedron-fields-of-agadeem'),
    (423618,'Horizon Boughs','plane','https://scryfall.com/card/opca/37/horizon-boughs'),
    (423619,'Immersturm','plane','https://scryfall.com/card/opca/38/immersturm'),
    (423620,'Isle of Vesuva','plane','https://scryfall.com/card/opca/39/isle-of-vesuva'),
    (423621,'Izzet Steam Maze','plane','https://scryfall.com/card/opca/40/izzet-steam-maze'),
    (423622,'Jund','plane','https://scryfall.com/card/opca/41/jund'),
    (423623,'Kessig','plane','https://scryfall.com/card/opca/42/kessig'),
    (423624,'Kharasha Foothills','plane','https://scryfall.com/card/opca/43/kharasha-foothills'),
    (423625,'Kilnspire District','plane','https://scryfall.com/card/opca/44/kilnspire-district'),
    (423626,'Krosa','plane','https://scryfall.com/card/opca/45/krosa'),
    (423627,'Lair of the Ashen Idol','plane','https://scryfall.com/card/opca/46/lair-of-the-ashen-idol'),
    (423628,'Lethe Lake','plane','https://scryfall.com/card/opca/47/lethe-lake'),
    (423629,'Llanowar','plane','https://scryfall.com/card/opca/48/llanowar'),
    (423631,'Minamo','plane','https://scryfall.com/card/opca/50/minamo'),
    (423632,'Mirrored Depths','plane','https://scryfall.com/card/opca/51/mirrored-depths'),
    (423633,'Mount Keralia','plane','https://scryfall.com/card/opca/52/mount-keralia'),
    (423634,'Murasa','plane','https://scryfall.com/card/opca/53/murasa'),
    (423635,'Naar Isle','plane','https://scryfall.com/card/opca/54/naar-isle'),
    (423636,'Naya','plane','https://scryfall.com/card/opca/55/naya'),
    (423637,'Nephalia','plane','https://scryfall.com/card/opca/56/nephalia'),
    (423638,'Norn''s Dominion','plane','https://scryfall.com/card/opca/57/norns-dominion'),
    (423639,'Onakke Catacomb','plane','https://scryfall.com/card/opca/58/onakke-catacomb'),
    (423640,'Orochi Colony','plane','https://scryfall.com/card/opca/59/orochi-colony'),
    (423641,'Orzhova','plane','https://scryfall.com/card/opca/60/orzhova'),
    (423642,'Otaria','plane','https://scryfall.com/card/opca/61/otaria'),
    (423643,'Panopticon','plane','https://scryfall.com/card/opca/62/panopticon'),
    (423644,'Pools of Becoming','plane','https://scryfall.com/card/opca/63/pools-of-becoming'),
    (423645,'Prahv','plane','https://scryfall.com/card/opca/64/prahv'),
    (423646,'Quicksilver Sea','plane','https://scryfall.com/card/opca/65/quicksilver-sea'),
    (423647,'Raven''s Run','plane','https://scryfall.com/card/opca/66/ravens-run'),
    (423648,'Sanctum of Serra','plane','https://scryfall.com/card/opca/67/sanctum-of-serra'),
    (423649,'Sea of Sand','plane','https://scryfall.com/card/opca/68/sea-of-sand'),
    (423650,'Selesnya Loft Gardens','plane','https://scryfall.com/card/opca/69/selesnya-loft-gardens'),
    (423651,'Shiv','plane','https://scryfall.com/card/opca/70/shiv'),
    (423652,'Skybreen','plane','https://scryfall.com/card/opca/71/skybreen'),
    (423653,'Sokenzan','plane','https://scryfall.com/card/opca/72/sokenzan'),
    (423654,'Stairs to Infinity','plane','https://scryfall.com/card/opca/73/stairs-to-infinity'),
    (423655,'Stensia','plane','https://scryfall.com/card/opca/74/stensia'),
    (423656,'Stronghold Furnace','plane','https://scryfall.com/card/opca/75/stronghold-furnace'),
    (423657,'Takenuma','plane','https://scryfall.com/card/opca/76/takenuma'),
    (423658,'Talon Gates','plane','https://scryfall.com/card/opca/77/talon-gates'),
    (423659,'Tazeem','plane','https://scryfall.com/card/opca/78/tazeem'),
    (423660,'Tember City','plane','https://scryfall.com/card/opca/79/tember-city'),
    (423591,'The Aether Flues','plane','https://scryfall.com/card/opca/10/the-aether-flues'),
    (423600,'The Dark Barony','plane','https://scryfall.com/card/opca/19/the-dark-barony'),
    (423603,'The Eon Fog','plane','https://scryfall.com/card/opca/22/the-eon-fog'),
    (423606,'The Fourth Sphere','plane','https://scryfall.com/card/opca/25/the-fourth-sphere'),
    (423613,'The Great Forest','plane','https://scryfall.com/card/opca/32/the-great-forest'),
    (423617,'The Hippodrome','plane','https://scryfall.com/card/opca/36/the-hippodrome'),
    (423630,'The Maelstrom','plane','https://scryfall.com/card/opca/49/the-maelstrom'),
    (423667,'The Zephyr Maze','plane','https://scryfall.com/card/opca/86/the-zephyr-maze'),
    (423661,'Trail of the Mage-Rings','plane','https://scryfall.com/card/opca/80/trail-of-the-mage-rings'),
    (423662,'Truga Jungle','plane','https://scryfall.com/card/opca/81/truga-jungle'),
    (423663,'Turri Island','plane','https://scryfall.com/card/opca/82/turri-island'),
    (423664,'Undercity Reaches','plane','https://scryfall.com/card/opca/83/undercity-reaches'),
    (423665,'Velis Vel','plane','https://scryfall.com/card/opca/84/velis-vel'),
    (423666,'Windriddle Palaces','plane','https://scryfall.com/card/opca/85/windriddle-palaces'),
    (423582,'Chaotic Aether','phenomenon','https://scryfall.com/card/opca/1/chaotic-aether'),
    (423583,'Interplanar Tunnel','phenomenon','https://scryfall.com/card/opca/2/interplanar-tunnel'),
    (423584,'Morphic Tide','phenomenon','https://scryfall.com/card/opca/3/morphic-tide'),
    (423585,'Mutual Epiphany','phenomenon','https://scryfall.com/card/opca/4/mutual-epiphany'),
    (423586,'Planewide Disaster','phenomenon','https://scryfall.com/card/opca/5/planewide-disaster'),
    (423587,'Reality Shaping','phenomenon','https://scryfall.com/card/opca/6/reality-shaping'),
    (423588,'Spatial Merging','phenomenon','https://scryfall.com/card/opca/7/spatial-merging'),
    (423589,'Time Distortion','phenomenon','https://scryfall.com/card/opca/8/time-distortion');
